language: go

install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v0.62.0/hugo_extended_0.62.0_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb

script:
  - hugo version

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
