language: go

install:
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
  - sudo dpkg -i hugo*.deb

script:
  - hugo version
  - 

global:
  - PRODUCTION=true
  - HUGO_RELEASE=0.54.0
  - secure: <a long string of random looking ASCII chars ending with an equal sign>
  - secure: <another long ASCII string ending with an equal sign>
  - secure: <and another long ASCII string ending with an equal sign>
